package ru.olgak.folks.soap;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2018-03-26T15:41:16.087+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://olgak.ru/folks/v1", name = "FolksWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-03-26T15:41:16.087+07:00", comments = "Apache CXF 3.1.11")
public interface FolksWS {

    @WebMethod(action = "http://olgak.ru/soap/services/folks/search")
    @WebResult(name = "searchResponse", targetNamespace = "http://olgak.ru/folks/v1", partName = "parameters")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2018-03-26T15:41:16.087+07:00")
    public SearchResponse search(
        @WebParam(partName = "parameters", name = "search", targetNamespace = "http://olgak.ru/folks/v1")
        Search parameters
    );
}
